import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Admin Access',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Image
          src="/spaceships.png"
          fill
          sizes="100vw"
          style={{
            objectFit: 'cover',
            zIndex: -1
          }}
        />
        {children}
      </body>
    </html>
  )
}
