version: "3.5"
services:
  frontend:
    build:
      context: src/frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

    stdin_open: true
    tty: true

  backend:
    build:
      context: src/backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
